{% set name = "readchar" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/magmax/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: af3ed7c85c28bccb59c82809c51de123c311aad7bb05463be102c71162523ec4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flake8
  run:
    - python >=3.6

test:
  imports:
    - readchar

about:
  home: https://github.com/magmax/python-readchar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to easily read single chars and key strokes.

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
